name: Check Formatting/Linting
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  push:
    branches: [master]
    tags: ['*']

env:
  cwd: ${{github.workspace}}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-build
  cancel-in-progress: true

jobs:
  check-formatting-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Skip lint (label)
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'skip lint')
        run: echo "Lint skipped via 'skip lint' label."

      - uses: actions/checkout@v5
        if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'skip lint')

      - name: Use Node.js 22
        if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'skip lint')
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'skip lint')
        run: npm ci
        working-directory: ${{github.workspace}}

      - name: Check formatting/linting
        if: github.event_name != 'pull_request' || !contains(github.event.pull_request.labels.*.name, 'skip lint')
        run: npm run lf:ci
